using System;
using System.Collections.Generic;
using System.Text;
using RimWorld;
using Verse;

namespace TG.StockGen
{
	/// <summary>
	/// Purchases specific pieces of apparel. When selling them, they have the color of the trader's ideology.
	/// Should be auto-generated by the TraderGen ideology feature.
	/// </summary>
	public class PreferredApparel : ConditionMatcher
	{
		public readonly HashSet<ThingDef> PreferredApparels = new HashSet<ThingDef>();

		public override void ConditionToText(ref StringBuilder b)
		{
			base.ConditionToText(ref b);
			Util.ToText(ref b, "PreferredApparels", PreferredApparels);
		}

		protected override bool CanBuy(in ThingDef def)
		{
			return def.IsApparel && PreferredApparels.Contains(def);
		}

		protected override IEnumerable<Thing> TryMakeForStock(ThingDef def, Faction faction)
		{
			if (!ModsConfig.IdeologyActive || faction.ideos?.PrimaryIdeo == null)
			{
				Logger.ErrorOnce("PreferredApparel should only be used when Ideology is active with trader having ideos.");
				yield break;
			}

			var color = faction.ideos.PrimaryIdeo.ApparelColor;
			foreach (var thing in base.TryMakeForStock(def, faction))
			{
				thing.SetColor(color);
				yield return thing;
			}
		}
	}
}