using System.Collections.Generic;
using System.Text;
using Verse;

namespace TG.StockGen
{
	/// <summary>
	/// Purchases specific pieces of apparel. When selling them, they have the color of the trader's ideology.
	/// Should be auto-generated by the TraderGen ideology feature.
	/// </summary>
	public class PreferredApparel : IdeoColorApparel
	{
		public readonly HashSet<ThingDef> PreferredApparels = new HashSet<ThingDef>();

		public override void ConditionToText(ref StringBuilder b)
		{
			base.ConditionToText(ref b);
			Util.ToText(ref b, "PreferredApparels", PreferredApparels);
		}

		protected override bool ApparelCondition(in ThingDef def)
		{
			return PreferredApparels.Contains(def);
		}
	}
}